 language: scala

 scala:
   - "2.11.8"

 jdk:
   - oraclejdk8

 script:
  - sbt test it:test

 sudo: required

 services:
   - docker

 install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq httpie

 before_script:
  - docker run --name ecommerce-event-store -d -p 2113:2113 -p 1113:1113 eventstore/eventstore
  - sleep 5
  - http -a admin:changeit POST ':2113/projection/$by_category/command/enable'
