 language: scala

 scala:
   - "2.12.2"

 jdk:
   - oraclejdk8

 cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

 script:
  - http -a admin:changeit :2113/projections/continuous name==tags_proj type==JS emit==1 < $TRAVIS_BUILD_DIR/akka-ddd/eventstore-akka-persistence/src/main/resources/tags.js
  - sbt test
  - sbt "it:test"
  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

 sudo: required

 services:
   - docker

 install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq httpie

 before_script:
  - docker run --name ecommerce-event-store -d -p 2113:2113 -p 1113:1113 -e EVENTSTORE_START_STANDARD_PROJECTIONS=true eventstore/eventstore